[package]
name = "rs-btc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
modulo = "0.1.2"
num-bigint = "0.4"